Radh 2
ChanR-Analytics/HS_Immersive_Website pull request #38
Opened 2020-12-20 14:24 UTC by someone20dz

here is my work 

- [ ] Date of Conference (If Time Permits: Timeline Effect)
- [ ] Conference Timings
- [ ] Layout and Rules
- [ ] Goal of Conference
- [ ] Intended Audience
- [ ] Scope of Speakers and Events

2020-12-20 14:26 UTC, someone20dz commented
the rest of the work isn't done still need information

2020-12-22 19:40 UTC, JAnanth approved these changes

2020-12-22 19:48 UTC, TheChanRProject requested changes
Fix typography for logo and ChanR title in About page. 

Change background image of timeline to a colored gradient.

2020-12-23 21:11 UTC, TheChanRProject approved these changes
Looks great, @someone20dz .

Approved. 👍

2020-12-23 21:11 UTC, TheChanRProject commented on chanr_hs_immersive.html
Add comments bro

2020-12-23 21:11 UTC, TheChanRProject commented on chanr_hs_immersive.html
> +                                                        </div>
Structure looks ok, but I'm wondering if the tag structuring is easy to follow or not. Might be hard for newcomer to follow along.

2020-12-23 21:11 UTC, TheChanRProject commented on chanr_hs_immersive.html
> +              </div>
This is very nice. Lovely use of gradient for the background.

2020-12-23 21:11 UTC, TheChanRProject commented on chanr_hs_immersive.html
>    <script src="./assets/js/plugins/presentation-page/main.js"></script>
Great! I like it

2020-12-23 21:12 UTC, someone20dz commented on chanr_hs_immersive.html
> +                                                        </div>
I can help explaining it was tricky to put it in this way in order to work

2020-12-23 21:13 UTC, merged

2020-12-23 21:13 UTC, TheChanRProject commented on chanr_hs_immersive.html
> +                                                        </div>
Thanks @someone20dz . It is looking nice overall though. 

I'll work on Speakers Page tomorrow.